version: '3.5'

services:

  mongo:
    image: mongo
    container_name: "mongodb"
    restart: always
    volumes:
        - /tmp/mongodbdata:/data/db
    networks:
        - mynet
    
    
  happyparking:
    image: happyparking:latest
    build: .
    container_name: "happyparking"
    restart: always
    networks:
        - mynet
    environment:
        - MONGODB_URL=mongodb

networks:
  mynet:
      name: mynet
      driver: bridge
